### ISSUE TITLE
smart suffix replacement bolstering

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#1204]
@jemorrison reports:

> If I run in the mode of setting the 'output-file' I do not get this error.
> I did an update to condo-dev and git fetch jwst.
> Is this a known bug   or maybe I am behind on something I need to update to my ifucube model. 
> Jane
```
----------------------------------------------------------------------
ERROR RUNNING STEP 'CubeBuildStep':
    'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/Users/morrison/git/jwst/jwst/stpipe/cmdline.py", line 320, in step_from_cmdline
    step.run(*positional)
  File "/Users/morrison/git/jwst/jwst/stpipe/step.py", line 425, in run
    result_id=result_id(idx)
  File "/Users/morrison/git/jwst/jwst/stpipe/step.py", line 797, in make_output_path
    name = match.group('root')
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by stscieisenhamer** [comment]
This issue is a side-effect of adding the `save_results` flag. If this flag is set for a direct run of a `Step`, where a pipeline or `strun` has not defined default output file names, this is the result.

Basic fix will be to make the error a bit cleaner and lower to a warning such that if code is running steps directly, the processing will not fail.
