### ISSUE TITLE
Update calspec3 to call IFU-specific outlier detection step

### ISSUE THREAD

**Issue by stsci-hack** [STScI-JWST/jwst#1286]
It was reported that "when I run calspec3 on an ASN of MIRI MRS exposures...the outlier_detection step still seem to be trying to call the imaging resample routine when trying to create resampled arrays".  This resulted in the code raising an Exception as shown in the traceback shown below.  

A version of outlier-detection, therefore, needs to be developed to support this mode of data, so that calspec3 can be updated to call a working version of this step.

```
2017-10-05 14:56:11,337 - stpipe.Spec3Pipeline.outlier_detection - INFO - Performing outlier detection on 4 inputs
2017-10-05 14:56:31,132 - stpipe.Spec3Pipeline.outlier_detection - WARNING - /user/bushouse/anaconda2/envs/myjwst/lib/python2.7/site-packages/gwcs/selector.py:433: RuntimeWarning: invalid value encountered in less_equal
  temp = np.where(np.logical_or(temp <= val_range[0],

2017-10-05 14:56:31,134 - stpipe.Spec3Pipeline.outlier_detection - WARNING - /user/bushouse/anaconda2/envs/myjwst/lib/python2.7/site-packages/gwcs/selector.py:434: RuntimeWarning: invalid value encountered in greater_equal
  temp >= val_range[1]),

----------------------------------------------------------------------
ERROR RUNNING STEP 'Spec3Pipeline':
    'WCS' object has no attribute 'wcsinfo'
Traceback (most recent call last):
  File "/user/bushouse/anaconda2/envs/myjwst/lib/python2.7/site-packages/jwst-0.7.8rc3.dev10-py2.7-linux-x86_64.egg/jwst/stpipe/cmdline.py", line 320, in step_from_cmdline
    step.run(*positional)
  File "/user/bushouse/anaconda2/envs/myjwst/lib/python2.7/site-packages/jwst-0.7.8rc3.dev10-py2.7-linux-x86_64.egg/jwst/stpipe/step.py", line 370, in run
    result = self.process(*args)
  File "/user/bushouse/anaconda2/envs/myjwst/lib/python2.7/site-packages/jwst-0.7.8rc3.dev10-py2.7-linux-x86_64.egg/jwst/pipeline/calwebb_spec3.py", line 125, in process
    result = self.outlier_detection(result)
  File "/user/bushouse/anaconda2/envs/myjwst/lib/python2.7/site-packages/jwst-0.7.8rc3.dev10-py2.7-linux-x86_64.egg/jwst/stpipe/step.py", line 370, in run
    result = self.process(*args)
  File "/user/bushouse/anaconda2/envs/myjwst/lib/python2.7/site-packages/jwst-0.7.8rc3.dev10-py2.7-linux-x86_64.egg/jwst/outlier_detection/outlier_detection_step.py", line 77, in process
    step.do_detection()
  File "/user/bushouse/anaconda2/envs/myjwst/lib/python2.7/site-packages/jwst-0.7.8rc3.dev10-py2.7-linux-x86_64.egg/jwst/outlier_detection/outlier_detection.py", line 118, in do_detection
    blendheaders=False, **pars)
  File "/user/bushouse/anaconda2/envs/myjwst/lib/python2.7/site-packages/jwst-0.7.8rc3.dev10-py2.7-linux-x86_64.egg/jwst/resample/resample.py", line 73, in __init__
    self.output_wcs = resample_utils.make_output_wcs(self.input_models)
  File "/user/bushouse/anaconda2/envs/myjwst/lib/python2.7/site-packages/jwst-0.7.8rc3.dev10-py2.7-linux-x86_64.egg/jwst/resample/resample_utils.py", line 52, in make_output_wcs
    output_wcs = wcs_from_spec_footprints(wcslist)
  File "/user/bushouse/anaconda2/envs/myjwst/lib/python2.7/site-packages/jwst-0.7.8rc3.dev10-py2.7-linux-x86_64.egg/jwst/resample/resample_utils.py", line 274, in wcs_from_spec_footprints
    transform = compute_spec_transform(fiducial, refwcs)
  File "/user/bushouse/anaconda2/envs/myjwst/lib/python2.7/site-packages/jwst-0.7.8rc3.dev10-py2.7-linux-x86_64.egg/jwst/resample/resample_utils.py", line 308, in compute_spec_transform
    cdelt1 = refwcs.wcsinfo.cdelt1 / 3600.
AttributeError: 'WCS' object has no attribute 'wcsinfo' 
```

**Comment by stsci-hack** [comment]
The work done in #1369 allowed the outlier_detection code to call the resample_spec step.
