### ISSUE TITLE
Flat_field can't handle NIRSpec CubeModel from BRIGHTOBJ mode

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#1329]
The NIRSpec bright object time series mode (EXP_TYPE=NRS_BRIGHTOBJ) uses the fixed slit S1600A1 and a subarray readout that contains only the region around the spectrum from this slit. All processing of these exposures through calwebb_spec2 is done using a CubeModel, because the per-integration data are to be preserved for time series observations. When the CubeModel is fed into the flat_field step, it throws an error:
```
2017-10-19 09:28:53,653 - stpipe.Spec2Pipeline.extract_2d - INFO - Step extract_2d done
2017-10-19 09:28:55,085 - stpipe.Spec2Pipeline.flat_field - INFO - Prefetch for DFLAT reference file is '/grp/crds/cache/references/jwst/jwst_nirspec_dflat_0002.fits'.
2017-10-19 09:28:55,085 - stpipe.Spec2Pipeline.flat_field - INFO - Prefetch for FFLAT reference file is '/grp/crds/cache/references/jwst/jwst_nirspec_fflat_0004.fits'.
2017-10-19 09:28:55,086 - stpipe.Spec2Pipeline.flat_field - INFO - Prefetch for FLAT reference file is 'N/A'.
2017-10-19 09:28:55,086 - stpipe.Spec2Pipeline.flat_field - INFO - Prefetch for SFLAT reference file is '/grp/crds/cache/references/jwst/jwst_nirspec_sflat_0010.fits'.
2017-10-19 09:28:55,157 - stpipe.Spec2Pipeline.flat_field - INFO - Step flat_field running with args (<jwst.datamodels.cube.CubeModel object at 0x10e073ba8>,).
----------------------------------------------------------------------
ERROR RUNNING STEP 'Spec2Pipeline':
    No attribute 'slits'
Traceback (most recent call last):
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/jwst-0.7.8rc3.dev44-py3.5-macosx-10.7-x86_64.egg/jwst/datamodels/properties.py", line 210, in __getattr__
    val = self._instance[attr]
KeyError: 'slits'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/jwst-0.7.8rc3.dev44-py3.5-macosx-10.7-x86_64.egg/jwst/stpipe/cmdline.py", line 320, in step_from_cmdline
    step.run(*positional)
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/jwst-0.7.8rc3.dev44-py3.5-macosx-10.7-x86_64.egg/jwst/stpipe/step.py", line 370, in run
    result = self.process(*args)
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/jwst-0.7.8rc3.dev44-py3.5-macosx-10.7-x86_64.egg/jwst/pipeline/calwebb_spec2.py", line 85, in process
    asn.filename
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/jwst-0.7.8rc3.dev44-py3.5-macosx-10.7-x86_64.egg/jwst/pipeline/calwebb_spec2.py", line 207, in process_exposure_product
    input = self.flat_field(input)
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/jwst-0.7.8rc3.dev44-py3.5-macosx-10.7-x86_64.egg/jwst/stpipe/step.py", line 370, in run
    result = self.process(*args)
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/jwst-0.7.8rc3.dev44-py3.5-macosx-10.7-x86_64.egg/jwst/flatfield/flat_field_step.py", line 142, in process
    d_flat_model, self.flat_suffix)
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/jwst-0.7.8rc3.dev44-py3.5-macosx-10.7-x86_64.egg/jwst/flatfield/flat_field.py", line 72, in do_correction
    d_flat_model, flat_suffix)
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/jwst-0.7.8rc3.dev44-py3.5-macosx-10.7-x86_64.egg/jwst/flatfield/flat_field.py", line 275, in do_NIRSpec_flat_field
    for (k, slit) in enumerate(output_model.slits):
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/jwst-0.7.8rc3.dev44-py3.5-macosx-10.7-x86_64.egg/jwst/datamodels/properties.py", line 213, in __getattr__
    raise AttributeError("No attribute '{0}'".format(attr))
AttributeError: No attribute 'slits'
```
because it assumes that all NIRSpec fixed-slit data will be fed to it in the form of a MultiSlitModel.

Flat_field needs to be updated to handle the CubeModel as input and apply the derived flat-field to each plane of the cube.

**Comment by philhodge** [comment]
Closed by PR #1351.
