### ISSUE TITLE
Problem with backward transform in NIRSPEC IFU

### ISSUE THREAD

**Issue by nden** [STScI-JWST/jwst#149]
Somewhere along the IFU backward transform the inputs and outputs are not matched, i.e. the overall transform needs another combination of `Mapping` and `Identity` models. The error is

Traceback (most recent call last):
  File "./compute_world_coordinates.py", line 206, in <module>
    ifu_coords(res.filename)
  File "./compute_world_coordinates.py", line 47, in ifu_coords
    ifu_slits = nirspec.nrs_ifu_wcs(model)
  File "/grp/hst/ssb/rhel6/ssbdev/python/lib/python2.7/site-packages/jwst_pipeline.assign_wcs-0.6-py2.7.egg/jwst_pipeline/assign_wcs/nirspec.py", line 926, in nrs_ifu_wcs
    wcs_list.append(nrs_wcs_set_input(input_model.meta.wcs, 0, i, wrange))
  File "/grp/hst/ssb/rhel6/ssbdev/python/lib/python2.7/site-packages/jwst_pipeline.assign_wcs-0.6-py2.7.egg/jwst_pipeline/assign_wcs/nirspec.py", line 816, in nrs_wcs_set_input
    slit2detector = slit_wcs.get_transform('slit_frame', 'detector')
  File "/home/dencheva/ssbvirt/ssbdev-rhel6/lib/python2.7/site-packages/gwcs-0.6.dev154-py2.7.egg/gwcs/wcs.py", line 117, in get_transform
    return functools.reduce(lambda x, y: x | y, transforms)
  File "/home/dencheva/ssbvirt/ssbdev-rhel6/lib/python2.7/site-packages/gwcs-0.6.dev154-py2.7.egg/gwcs/wcs.py", line 117, in <lambda>
    return functools.reduce(lambda x, y: x | y, transforms)
  File "/home/dencheva/ssbvirt/ssbdev-rhel6/lib/python2.7/site-packages/astropy-1.3.dev15941-py2.7-linux-x86_64.egg/astropy/modeling/core.py", line 76, in <lambda>
    left, right, **kwargs)
  File "/home/dencheva/ssbvirt/ssbdev-rhel6/lib/python2.7/site-packages/astropy-1.3.dev15941-py2.7-linux-x86_64.egg/astropy/modeling/core.py", line 1977, in _from_operator
    inputs, outputs = mcls._check_inputs_and_outputs(operator, left, right)
  File "/home/dencheva/ssbvirt/ssbdev-rhel6/lib/python2.7/site-packages/astropy-1.3.dev15941-py2.7-linux-x86_64.egg/astropy/modeling/core.py", line 2038, in _check_inputs_and_outputs
    right.n_inputs, right.n_outputs))
astropy.modeling.core.ModelDefinitionError: Unsupported operands for |: None (n_inputs=3, n_outputs=3) and None (n_inputs=5, n_outputs=4); n_outputs for the left-hand model must match n_inputs for the right-hand model.

**Comment by nden** [comment]
This was caused by an attempt to change the final units from meters to microns. That attempt was reverted so this issue can be closed. However the units still need to be converted to microns (#155).
