### ISSUE TITLE
calspec3 outlier detection on 1 MIRI LRS fixed-slit exposure

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#1647]
A calspec3 ASN in the DMS test suite is currently failing in the outlier_detection step. The ASN is:

/ifs/int/jwstc/store/doggett/tests/SICDIL/cstring/JWSTDP-2018_1-171222/2018-01-03-224524/sdp/asn_creation/cal/level3/jw80600-o013_20180103t225333_spec3_001_asn.json

(on the DMS C-string VM, which is accessible as server "owlc-2"), which contains a single MIRI LRS fixed-slit exposure:

`{
    "asn_pool": "jw80600_20180103T225333_pool",
    "asn_rule": "candidate_Asn_MIRI_LRS_FIXEDSLIT",
    "constraints": "Constraints:\n    instrument: {'miri'}\n    is_not_tso: set()\n    asn_candidate: {\"\\\\(\\\\'o013\\\\'\\\\,\\\\ \\\\'observation\\\\'\\\\)\"}\n    opt_elem: {'p750l'}\n    exp_type: {'mir_lrs\\\\-fixedslit'}\n    subarray: {'full'}\n    program: {'80600'}\n    target: {'1'}",
    "target": "t001",
    "asn_id": "o013",
    "products": [
        {
            "members": [
                {
                    "expname": "jw80600013001_02101_00001_mirimage_cal.fits",
                    "asn_candidate": "('o013', 'observation')",
                    "exptype": "science",
                    "exposerr": "null"
                }
            ],
            "name": "jw80600-o013_t001_miri_p750l"
        }
    ],
    "degraded_status": "No known degraded exposures in association.",
    "code_version": "0.9.4",
    "program": "80600",
    "asn_type": "spec3",
    "version_id": "20180103T225333"
}`

The error is:

2018-01-04 08:50:04,721 - stpipe.Spec3Pipeline - INFO - Step Spec3Pipeline running with args ('/ifs/int/jwstc/store/doggett/tests/SICDIL/cstring/JWSTDP-2018_1-171222/2018-01-03-224524/sdp/asn_creation/cal/leve
l3/jw80600-o013_20180103t225333_spec3_001_asn.json',).
2018-01-04 08:50:04,721 - stpipe.Spec3Pipeline - INFO - Starting calwebb_spec3 ...
2018-01-04 08:50:05,239 - stpipe.Spec3Pipeline.outlier_detection - INFO - Step outlier_detection running with args (<jwst.datamodels.container.ModelContainer object at 0x2aef8d04fd68>,).
2018-01-04 08:50:05,253 - stpipe.Spec3Pipeline.outlier_detection - INFO - Performing outlier detection on 1 inputs
CRDS - DEBUG -  Using cached bestrefs for 'jw80600013001_02101_00001_mirimage_cal.fits' with types ['gain']
CRDS - DEBUG -  Using cached bestrefs for 'jw80600013001_02101_00001_mirimage_cal.fits' with types ['readnoise']
2018-01-04 08:50:05,803 - stpipe.Spec3Pipeline.outlier_detection - WARNING - /ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.9.0-py35/lib/python3.5/site-packages/astropy/coordinates/angles.py:637: Runtim
eWarning: invalid value encountered in less
  if np.any(self_angle < wrap_angle_floor) or np.any(self_angle >= wrap_angle):

2018-01-04 08:50:05,805 - stpipe.Spec3Pipeline.outlier_detection - WARNING - /ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.9.0-py35/lib/python3.5/site-packages/astropy/coordinates/angles.py:637: Runtim
eWarning: invalid value encountered in greater_equal
  if np.any(self_angle < wrap_angle_floor) or np.any(self_angle >= wrap_angle):

2018-01-04 08:50:05,805 - stpipe.Spec3Pipeline.outlier_detection - WARNING - /ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.9.0-py35/lib/python3.5/site-packages/astropy/coordinates/angles.py:520: Runtim
eWarning: invalid value encountered in less
  if np.any(angles.value < lower) or np.any(angles.value > upper):

2018-01-04 08:50:05,806 - stpipe.Spec3Pipeline.outlier_detection - WARNING - /ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.9.0-py35/lib/python3.5/site-packages/astropy/coordinates/angles.py:520: Runtim
eWarning: invalid value encountered in greater
  if np.any(angles.value < lower) or np.any(angles.value > upper):

2018-01-04 08:50:05,963 - stpipe.Spec3Pipeline.outlier_detection - WARNING - /ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.9.0-py35/lib/python3.5/site-packages/astropy/modeling/rotations.py:186: Runtim
eWarning: invalid value encountered in less
  mask = alpha < 0

2018-01-04 08:50:06,320 - stpipe.Spec3Pipeline.outlier_detection - INFO - Resampling slit (387, 43)
2018-01-04 08:50:07,622 - stpipe.Spec3Pipeline.outlier_detection - INFO - Drizzling (1024, 1032) --> (387, 43)
2018-01-04 08:50:07,756 - stpipe.Spec3Pipeline.outlier_detection - WARNING - /ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.9.0-py35/lib/python3.5/site-packages/astropy/stats/sigma_clipping.py:155: Runt
imeWarning: invalid value encountered in greater
  _filtered_data.mask |= _filtered_data > max_value

2018-01-04 08:50:07,757 - stpipe.Spec3Pipeline.outlier_detection - WARNING - /ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.9.0-py35/lib/python3.5/site-packages/astropy/stats/sigma_clipping.py:156: Runt
imeWarning: invalid value encountered in less
  _filtered_data.mask |= _filtered_data < min_value

Traceback (most recent call last):
  File "/ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.9.0-py35/lib/python3.5/site-packages/jwst-0.9.0-py3.5-linux-x86_64.egg/EGG-INFO/scripts/strun", line 14, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.9.0-py35/lib/python3.5/site-packages/jwst-0.9.0-py3.5-linux-x86_64.egg/jwst/stpipe/step.py", line 147, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.9.0-py35/lib/python3.5/site-packages/jwst-0.9.0-py3.5-linux-x86_64.egg/jwst/stpipe/cmdline.py", line 299, in step_from_cmdline
    step.run(*positional)
  File "/ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.9.0-py35/lib/python3.5/site-packages/jwst-0.9.0-py3.5-linux-x86_64.egg/jwst/stpipe/step.py", line 366, in run
    step_result = self.process(*args)
  File "/ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.9.0-py35/lib/python3.5/site-packages/jwst-0.9.0-py3.5-linux-x86_64.egg/jwst/pipeline/calwebb_spec3.py", line 125, in process
    result = self.outlier_detection(result)
  File "/ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.9.0-py35/lib/python3.5/site-packages/jwst-0.9.0-py3.5-linux-x86_64.egg/jwst/stpipe/step.py", line 366, in run
    step_result = self.process(*args)
  File "/ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.9.0-py35/lib/python3.5/site-packages/jwst-0.9.0-py3.5-linux-x86_64.egg/jwst/outlier_detection/outlier_detection_step.py", line 145, in process
    step.do_detection()
  File "/ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.9.0-py35/lib/python3.5/site-packages/jwst-0.9.0-py3.5-linux-x86_64.egg/jwst/outlier_detection/outlier_detection_spec.py", line 96, in do_detection
    median_model.data = self.create_median(drizzled_models)
  File "/ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.9.0-py35/lib/python3.5/site-packages/jwst-0.9.0-py3.5-linux-x86_64.egg/jwst/outlier_detection/outlier_detection.py", line 272, in create_median
    badmasks=badmasks)
  File "/ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.9.0-py35/lib/python3.5/site-packages/stsci.image-2.2.0.dev0-py3.5-linux-x86_64.egg/stsci/image/combine.py", line 137, in median
    return _combine_f("median", arrays, output, outtype, nlow, nhigh, badmasks)
  File "/ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.9.0-py35/lib/python3.5/site-packages/stsci.image-2.2.0.dev0-py3.5-linux-x86_64.egg/stsci/image/combine.py", line 21, in _combine_f
    _combine(arrays, out, nlow, nhigh, badmasks, funcstr)
TypeError: Cannot cast array data from dtype('float64') to dtype('uint8') according to the rule 'safe'

Not sure what exactly is causing this particular error, but it seems to me that there ought to be a hook in either the calwebb_spec3 pipeline or the outlier_detection step, such that outlier_detection doesn't get called for an ASN containing 1 exposure.

**Comment by hbushouse** [comment]
Fixed by #1787.
