### ISSUE TITLE
make_header script for NRC_CORON exposure types

### ISSUE THREAD

**Issue by aliciacanipe** [STScI-JWST/jwst#1986]
Hello,

I was just doing some make_header tests for different NIRCam exposure types. Will the tool eventually be able to provide the headers for calwebb_coron3? Right now it doesn't seem to know the pipeline for that exposure type: 

`(jwstdev05012018) bash-4.1$ make_header NIRCAM NRC_IMAGE 3 test_image3exptype.fits
(jwstdev05012018) bash-4.1$ make_header NIRCAM NRC_GRISM 3 test_spec3exptype.fits
(jwstdev05012018) bash-4.1$ make_header NIRCAM NRC_TSIMAGE 3 test_tso3exptype.fits
(jwstdev05012018) bash-4.1$ make_header NIRCAM NRC_CORON 3 test_coron3exptype.fits
Traceback (most recent call last):
  File "/user/acanipe/miniconda3/envs/jwstdev05012018/bin/make_header", line 4, in <module>
    __import__('pkg_resources').run_script('jwst==0.9.3a0.dev165+gde4a626a', 'make_header')
  File "/user/acanipe/miniconda3/envs/jwstdev05012018/lib/python3.6/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/user/acanipe/miniconda3/envs/jwstdev05012018/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/user/acanipe/miniconda3/envs/jwstdev05012018/lib/python3.6/site-packages/jwst-0.9.3a0.dev165+gde4a626a-py3.6-linux-x86_64.egg/EGG-INFO/scripts/make_header", line 722, in <module>
    im = main(args.instrument, args.mode, args.level)
  File "/user/acanipe/miniconda3/envs/jwstdev05012018/lib/python3.6/site-packages/jwst-0.9.3a0.dev165+gde4a626a-py3.6-linux-x86_64.egg/EGG-INFO/scripts/make_header", line 78, in main
    pipeline = choose_pipeline(defaults)
  File "/user/acanipe/miniconda3/envs/jwstdev05012018/lib/python3.6/site-packages/jwst-0.9.3a0.dev165+gde4a626a-py3.6-linux-x86_64.egg/EGG-INFO/scripts/make_header", line 242, in choose_pipeline
    exposure_type)
ValueError: Pipeline not defined for mode NRC_CORON`

The files for the first 3 modes/pipelines are created: 

393368 -rwxrwxr-x  1 acanipe  STSCI\wit  201404160 May  4 10:10 test_tso3exptype.fits
393368 -rwxrwxr-x  1 acanipe  STSCI\wit  201404160 May  4 10:10 test_spec3exptype.fits
393368 -rwxrwxr-x  1 acanipe  STSCI\wit  201404160 May  4 10:10 test_image3exptype.fits

Thank you,
Alicia

**Comment by hbushouse** [comment]
Fixed by #1990
