### ISSUE TITLE
resample_spec error for NIRSpec fixed-slit exposures

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#2039]
There are several examples of NIRSpec fixed-slit exposures in the DMS test suite that are failing in the resample_spec step of the calwebb_spec2 pipeline. The traceback is:
```
2018-05-17 12:51:14,385 - stpipe.Spec2Pipeline.photom - INFO - Step photom done
2018-05-17 12:51:14,434 - stpipe.Spec2Pipeline.resample_spec - INFO - Step resample_spec running with args (<MultiSlitModel from jw84600004001_02102_00001_nrs2_rate.fits>,).
----------------------------------------------------------------------
ERROR RUNNING STEP 'Spec2Pipeline':
    Expected input arrays to have the same shape
Traceback (most recent call last):
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/jwst-0.9.4a0.dev17-py3.5-macosx-10.7-x86_64.egg/jwst/stpipe/cmdline.py", line 297, in step_from_cmdline
    step.run(*positional)
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/jwst-0.9.4a0.dev17-py3.5-macosx-10.7-x86_64.egg/jwst/stpipe/step.py", line 391, in run
    step_result = self.process(*args)
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/jwst-0.9.4a0.dev17-py3.5-macosx-10.7-x86_64.egg/jwst/pipeline/calwebb_spec2.py", line 86, in process
    asn.filename
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/jwst-0.9.4a0.dev17-py3.5-macosx-10.7-x86_64.egg/jwst/pipeline/calwebb_spec2.py", line 251, in process_exposure_product
    resamp = self.resample_spec(input)
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/jwst-0.9.4a0.dev17-py3.5-macosx-10.7-x86_64.egg/jwst/stpipe/step.py", line 391, in run
    step_result = self.process(*args)
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/jwst-0.9.4a0.dev17-py3.5-macosx-10.7-x86_64.egg/jwst/resample/resample_spec_step.py", line 56, in process
    good_bits=self.good_bits)
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/jwst-0.9.4a0.dev17-py3.5-macosx-10.7-x86_64.egg/jwst/resample/resample_spec.py", line 83, in __init__
    self.output_wcs = self.build_nirspec_output_wcs()
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/jwst-0.9.4a0.dev17-py3.5-macosx-10.7-x86_64.egg/jwst/resample/resample_spec.py", line 153, in build_nirspec_output_wcs
    grid_slit = Grid(*ref_det2slit(*grid))
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/astropy/modeling/core.py", line 382, in __call__
    ('equivalencies', None)])
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/astropy/modeling/core.py", line 363, in __call__
    return super(cls, self).__call__(*inputs, **kwargs)
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/astropy/modeling/core.py", line 803, in __call__
    outputs = self.evaluate(*chain(inputs, parameters))
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/astropy/modeling/core.py", line 2909, in evaluate
    return self.__class__.evaluate(*args)
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/astropy/modeling/core.py", line 2350, in evaluate
    result = cls._evaluate(inputs, params)
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/astropy/modeling/core.py", line 2182, in <lambda>
    return (lambda inputs, params: g[0](f[0](inputs, params), params),
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/astropy/modeling/core.py", line 2182, in <lambda>
    return (lambda inputs, params: g[0](f[0](inputs, params), params),
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/astropy/modeling/core.py", line 2182, in <lambda>
    return (lambda inputs, params: g[0](f[0](inputs, params), params),
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/astropy/modeling/core.py", line 2182, in <lambda>
    return (lambda inputs, params: g[0](f[0](inputs, params), params),
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/astropy/modeling/core.py", line 2182, in <lambda>
    return (lambda inputs, params: g[0](f[0](inputs, params), params),
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/astropy/modeling/core.py", line 2193, in <lambda>
    return (lambda inputs, params: (f[0](inputs[:f[1]], params) +
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/astropy/modeling/core.py", line 2194, in <lambda>
    g[0](inputs[f[1]:], params)),
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/astropy/modeling/core.py", line 2182, in <lambda>
    return (lambda inputs, params: g[0](f[0](inputs, params), params),
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/astropy/modeling/core.py", line 2182, in <lambda>
    return (lambda inputs, params: g[0](f[0](inputs, params), params),
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/astropy/modeling/core.py", line 2182, in <lambda>
    return (lambda inputs, params: g[0](f[0](inputs, params), params),
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/astropy/modeling/core.py", line 2790, in f
    return evaluate_wrapper(model, inputs, param_values)
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/astropy/modeling/core.py", line 2782, in evaluate_wrapper
    outputs = model.evaluate(*inputs, *param_values)
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.5/site-packages/astropy/modeling/rotations.py", line 371, in evaluate
    raise ValueError("Expected input arrays to have the same shape")
ValueError: Expected input arrays to have the same shape
```
Example input _rate files that show this problem can be found in:
/grp/jwst/ssb/bushouse/jwst_data/NIRSpec/FS/

and the files are:
jw84600002001_02101_00001_nrs2_rate.fits
jw84600003001_02103_00001_nrs2_rate.fits
jw84600004001_02101_00001_nrs2_rate.fits
jw84600004001_02102_00001_nrs2_rate.fits

**Comment by nden** [comment]
Is there a chance they are running an old version of astropy? I thought this was fixed already.

**Comment by hbushouse** [comment]
I just reran these myself using the latest dev and got that error. Although I don't recall how long it's been since I updated astropy in my environment (it may have been as much as 2 weeks ago). How long ago was a fix put into astropy?

**Comment by nden** [comment]
Github says it was merged 19 days ago.

**Comment by hbushouse** [comment]
@nden is correct (as always). After updating to the latest version of astropy, all of these datasets now process cleanly all the way through calwebb_spec2.

Never mind.
