### ISSUE TITLE
Extract_2d fails with I/O operation on closed file on NIRSPEC IFU data

### ISSUE THREAD

**Issue by stscirij** [STScI-JWST/jwst#432]
Here's the traceback, all of the data are in /user/rij/jwst/test/test_pathloss

(pathloss) bash-4.1$ strun jwst.extract_2d.Extract2dStep jw00011001001_01117_00001_NRS1_rate_AssignWcsStep.fits
2016-11-08 16:01:54,838 - stpipe.Extract2dStep - INFO - Extract2dStep instance created.
2016-11-08 16:01:55,400 - stpipe.Extract2dStep - INFO - Step Extract2dStep running with args ('jw00011001001_01117_00001_NRS1_rate_AssignWcsStep.fits',).
2016-11-08 16:02:18,967 - stpipe.Extract2dStep - INFO - EXP_TYPE is NRS_IFU
----------------------------------------------------------------------
ERROR RUNNING STEP 'Extract2dStep':
    I/O operation on closed file
Traceback (most recent call last):
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/astropy/utils/decorators.py", line 497, in __get__
    return obj.__dict__[self._key]
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/jwst-0.7.0rc2.dev74-py3.5-linux-x86_64.egg/jwst/stpipe/cmdline.py", line 275, in step_from_cmdline
    step.run(*positional)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/jwst-0.7.0rc2.dev74-py3.5-linux-x86_64.egg/jwst/stpipe/step.py", line 373, in run
    result.meta.calibration_software_revision = __version_commit__ #__svn_revision__
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/jwst-0.7.0rc2.dev74-py3.5-linux-x86_64.egg/jwst/datamodels/properties.py", line 206, in __setattr__
    self._validate()
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/jwst-0.7.0rc2.dev74-py3.5-linux-x86_64.egg/jwst/datamodels/properties.py", line 155, in _validate
    self._instance, self._ctx._asdf)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/yamlutil.py", line 238, in custom_tree_to_tagged_tree
    return treeutil.walk_and_modify(tree, walker)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/treeutil.py", line 188, in walk_and_modify
    return recurse(top)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/treeutil.py", line 133, in recurse
    val = recurse(val)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/treeutil.py", line 149, in recurse
    result = callback(result)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/yamlutil.py", line 235, in walker
    return tag.to_tree_tagged(node, ctx)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/asdftypes.py", line 462, in to_tree_tagged
    obj = cls.to_tree(node, ctx)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/tags/wcs/wcs.py", line 52, in to_tree
    'steps': yamlutil.custom_tree_to_tagged_tree(steps, ctx)}
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/yamlutil.py", line 238, in custom_tree_to_tagged_tree
    return treeutil.walk_and_modify(tree, walker)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/treeutil.py", line 188, in walk_and_modify
    return recurse(top)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/treeutil.py", line 142, in recurse
    [recurse(val) for val in tree])
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/treeutil.py", line 142, in <listcomp>
    [recurse(val) for val in tree])
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/treeutil.py", line 133, in recurse
    val = recurse(val)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/treeutil.py", line 149, in recurse
    result = callback(result)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/yamlutil.py", line 235, in walker
    return tag.to_tree_tagged(node, ctx)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/tags/transform/compound.py", line 95, in to_tree_tagged
    node = cls._to_tree_from_model_tree(model._tree, ctx)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/tags/transform/compound.py", line 79, in _to_tree_from_model_tree
    right = cls._to_tree_from_model_tree(tree.right, ctx)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/tags/transform/compound.py", line 73, in _to_tree_from_model_tree
    left = cls._to_tree_from_model_tree(tree.left, ctx)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/tags/transform/compound.py", line 73, in _to_tree_from_model_tree
    left = cls._to_tree_from_model_tree(tree.left, ctx)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/tags/transform/compound.py", line 73, in _to_tree_from_model_tree
    left = cls._to_tree_from_model_tree(tree.left, ctx)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/tags/transform/compound.py", line 79, in _to_tree_from_model_tree
    right = cls._to_tree_from_model_tree(tree.right, ctx)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/tags/transform/compound.py", line 71, in _to_tree_from_model_tree
    tree.left.value, ctx)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/yamlutil.py", line 238, in custom_tree_to_tagged_tree
    return treeutil.walk_and_modify(tree, walker)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/treeutil.py", line 188, in walk_and_modify
    return recurse(top)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/treeutil.py", line 149, in recurse
    result = callback(result)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/yamlutil.py", line 235, in walker
    return tag.to_tree_tagged(node, ctx)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/asdftypes.py", line 462, in to_tree_tagged
    obj = cls.to_tree(node, ctx)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/tags/transform/basic.py", line 75, in to_tree
    node = cls.to_tree_transform(model, ctx)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/tags/transform/projections.py", line 39, in to_tree_transform
    return yamlutil.custom_tree_to_tagged_tree(node, ctx)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/yamlutil.py", line 238, in custom_tree_to_tagged_tree
    return treeutil.walk_and_modify(tree, walker)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/treeutil.py", line 188, in walk_and_modify
    return recurse(top)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/treeutil.py", line 133, in recurse
    val = recurse(val)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/treeutil.py", line 149, in recurse
    result = callback(result)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/yamlutil.py", line 235, in walker
    return tag.to_tree_tagged(node, ctx)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/asdftypes.py", line 462, in to_tree_tagged
    obj = cls.to_tree(node, ctx)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/tags/core/ndarray.py", line 393, in to_tree
    block = ctx.blocks.find_or_create_block_for_array(data, ctx)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/fits_embed.py", line 97, in find_or_create_block_for_array
    if base is hdu.data:
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/astropy/utils/decorators.py", line 499, in __get__
    val = self.fget(obj)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/astropy/io/fits/hdu/image.py", line 243, in data
    data = self._get_scaled_image_data(self._data_offset, self.shape)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/astropy/io/fits/hdu/image.py", line 700, in _get_scaled_image_data
    raw_data = self._get_raw_data(shape, code, offset)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/astropy/io/fits/hdu/base.py", line 567, in _get_raw_data
    return self._file.readarray(offset=offset, dtype=code, shape=shape)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/astropy/io/fits/file.py", line 269, in readarray
    dtype=np.uint8)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/numpy/core/memmap.py", line 223, in __new__
    fid.seek(0, 2)
ValueError: I/O operation on closed file

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/astropy/utils/decorators.py", line 497, in __get__
    return obj.__dict__[self._key]
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/jwst-0.7.0rc2.dev74-py3.5-linux-x86_64.egg/EGG-INFO/scripts/strun", line 14, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/jwst-0.7.0rc2.dev74-py3.5-linux-x86_64.egg/jwst/stpipe/step.py", line 128, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/jwst-0.7.0rc2.dev74-py3.5-linux-x86_64.egg/jwst/stpipe/cmdline.py", line 275, in step_from_cmdline
    step.run(*positional)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/jwst-0.7.0rc2.dev74-py3.5-linux-x86_64.egg/jwst/stpipe/step.py", line 373, in run
    result.meta.calibration_software_revision = __version_commit__ #__svn_revision__
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/jwst-0.7.0rc2.dev74-py3.5-linux-x86_64.egg/jwst/datamodels/properties.py", line 206, in __setattr__
    self._validate()
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/jwst-0.7.0rc2.dev74-py3.5-linux-x86_64.egg/jwst/datamodels/properties.py", line 155, in _validate
    self._instance, self._ctx._asdf)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/yamlutil.py", line 238, in custom_tree_to_tagged_tree
    return treeutil.walk_and_modify(tree, walker)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/treeutil.py", line 188, in walk_and_modify
    return recurse(top)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/treeutil.py", line 133, in recurse
    val = recurse(val)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/treeutil.py", line 149, in recurse
    result = callback(result)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/yamlutil.py", line 235, in walker
    return tag.to_tree_tagged(node, ctx)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/asdftypes.py", line 462, in to_tree_tagged
    obj = cls.to_tree(node, ctx)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/tags/wcs/wcs.py", line 52, in to_tree
    'steps': yamlutil.custom_tree_to_tagged_tree(steps, ctx)}
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/yamlutil.py", line 238, in custom_tree_to_tagged_tree
    return treeutil.walk_and_modify(tree, walker)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/treeutil.py", line 188, in walk_and_modify
    return recurse(top)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/treeutil.py", line 142, in recurse
    [recurse(val) for val in tree])
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/treeutil.py", line 142, in <listcomp>
    [recurse(val) for val in tree])
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/treeutil.py", line 133, in recurse
    val = recurse(val)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/treeutil.py", line 149, in recurse
    result = callback(result)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/yamlutil.py", line 235, in walker
    return tag.to_tree_tagged(node, ctx)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/tags/transform/compound.py", line 95, in to_tree_tagged
    node = cls._to_tree_from_model_tree(model._tree, ctx)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/tags/transform/compound.py", line 79, in _to_tree_from_model_tree
    right = cls._to_tree_from_model_tree(tree.right, ctx)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/tags/transform/compound.py", line 73, in _to_tree_from_model_tree
    left = cls._to_tree_from_model_tree(tree.left, ctx)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/tags/transform/compound.py", line 73, in _to_tree_from_model_tree
    left = cls._to_tree_from_model_tree(tree.left, ctx)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/tags/transform/compound.py", line 73, in _to_tree_from_model_tree
    left = cls._to_tree_from_model_tree(tree.left, ctx)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/tags/transform/compound.py", line 79, in _to_tree_from_model_tree
    right = cls._to_tree_from_model_tree(tree.right, ctx)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/tags/transform/compound.py", line 71, in _to_tree_from_model_tree
    tree.left.value, ctx)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/yamlutil.py", line 238, in custom_tree_to_tagged_tree
    return treeutil.walk_and_modify(tree, walker)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/treeutil.py", line 188, in walk_and_modify
    return recurse(top)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/treeutil.py", line 149, in recurse
    result = callback(result)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/yamlutil.py", line 235, in walker
    return tag.to_tree_tagged(node, ctx)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/asdftypes.py", line 462, in to_tree_tagged
    obj = cls.to_tree(node, ctx)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/tags/transform/basic.py", line 75, in to_tree
    node = cls.to_tree_transform(model, ctx)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/tags/transform/projections.py", line 39, in to_tree_transform
    return yamlutil.custom_tree_to_tagged_tree(node, ctx)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/yamlutil.py", line 238, in custom_tree_to_tagged_tree
    return treeutil.walk_and_modify(tree, walker)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/treeutil.py", line 188, in walk_and_modify
    return recurse(top)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/treeutil.py", line 133, in recurse
    val = recurse(val)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/treeutil.py", line 149, in recurse
    result = callback(result)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/yamlutil.py", line 235, in walker
    return tag.to_tree_tagged(node, ctx)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/asdftypes.py", line 462, in to_tree_tagged
    obj = cls.to_tree(node, ctx)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/tags/core/ndarray.py", line 393, in to_tree
    block = ctx.blocks.find_or_create_block_for_array(data, ctx)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/asdf/fits_embed.py", line 97, in find_or_create_block_for_array
    if base is hdu.data:
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/astropy/utils/decorators.py", line 499, in __get__
    val = self.fget(obj)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/astropy/io/fits/hdu/image.py", line 243, in data
    data = self._get_scaled_image_data(self._data_offset, self.shape)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/astropy/io/fits/hdu/image.py", line 700, in _get_scaled_image_data
    raw_data = self._get_raw_data(shape, code, offset)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/astropy/io/fits/hdu/base.py", line 567, in _get_raw_data
    return self._file.readarray(offset=offset, dtype=code, shape=shape)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/astropy/io/fits/file.py", line 269, in readarray
    dtype=np.uint8)
  File "/user/rij/anaconda3/envs/pathloss/lib/python3.5/site-packages/numpy/core/memmap.py", line 223, in __new__
    fid.seek(0, 2)
ValueError: I/O operation on closed file
(pathloss) bash-4.1$

**Comment by nden** [comment]
@stscirij Should this be closed now? Is it resolved?

**Comment by stscirij** [comment]
Yes, this was my mistake trying to run extract_2d of a NIRSPEC IFU dataset
