### ISSUE TITLE
stspec exceptions

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#649]
When attempting to run stspec, the following occurs:
```
$ stspec jwst.pipeline.Spec2Pipeline
Traceback (most recent call last):
  File "/Users/eisenham/anaconda3/envs/jwstdev_py3/bin/stspec", line 4, in <module>
    __import__('pkg_resources').run_script('jwst==0.7.7.dev138', 'stspec')
  File "/Users/eisenham/anaconda3/envs/jwstdev_py3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/eisenham/anaconda3/envs/jwstdev_py3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/Users/eisenham/anaconda3/envs/jwstdev_py3/lib/python3.5/site-packages/jwst-0.7.7.dev138-py3.5-macosx-10.6-x86_64.egg/EGG-INFO/scripts/stspec", line 31, in <module>
    step_class.print_configspec()
  File "/Users/eisenham/anaconda3/envs/jwstdev_py3/lib/python3.5/site-packages/jwst-0.7.7.dev138-py3.5-macosx-10.6-x86_64.egg/jwst/stpipe/step.py", line 60, in print_configspec
    specfile.write(stream)
  File "/Users/eisenham/anaconda3/envs/jwstdev_py3/lib/python3.5/site-packages/jwst-0.7.7.dev138-py3.5-macosx-10.6-x86_64.egg/jwst/stpipe/configobj/configobj.py", line 2054, in write
    outfile.write(output.encode())
TypeError: write() argument must be str, not bytes
```

**Comment by hbushouse** [comment]
In the infamous words of help desker's everywhere, "Works for me!"

% stspec jwst.pipeline.Spec2Pipeline
pre_hooks = string_list(default=list())
post_hooks = string_list(default=list())

output_dir = string(default=None)# Directory path for output files
output_file = output_file(default=None)# File to save output to.
skip = boolean(default=False)# Skip this step
save_bsub = boolean(default=False)
[steps]
[[pathloss]]
pre_hooks = string_list(default=list())
post_hooks = string_list(default=list())

output_dir = string(default=None)# Directory path for output files
output_file = output_file(default=None)# File to save output to.
skip = boolean(default=False)# Skip this step
override_pathloss = string(default=None)# Override the pathloss reference file
config_file = string(default=None)
name = string(default='')
class = string(default='')
[[assign_wcs]]
pre_hooks = string_list(default=list())
post_hooks = string_list(default=list())

output_dir = string(default=None)# Directory path for output files
output_file = output_file(default=None)# File to save output to.
skip = boolean(default=False)# Skip this step
.... [snip]


But I'm running a py2.7 installation, so perhaps it's a py3.5 issue.

**Comment by stscieisenhamer** [comment]
Yes, I suspect it is, considering the exception.
