### ISSUE TITLE
Fix failing pandokia tests

### ISSUE THREAD

**Issue by pllim** [STScI-JWST/jwst#674]
See https://ssb.stsci.edu/pandokia/pandokia.cgi?query=summary&qid=5204

**Comment by pllim** [comment]
Two more need fixing.

https://ssb.stsci.edu/pandokia/pandokia.cgi?query=detail&key_id=44103585

```
Traceback (most recent call last):
  File "/data4/iraf_conda/bldtmp/porcelain.OiakD22947/porcelain/envs/dev/lib/python2.7/site-packages/pandokia/helpers/runner_minipyt.py", line 583, in process_file
    module = imp.load_source( module_name, filename )
  File "docbuild.py", line 22, in <module>
    f=open("/eng/ssb/websites/ssbpublic/doc/jwst_git/stat_summary.csv","r")
IOError: [Errno 2] No such file or directory: '/eng/ssb/websites/ssbpublic/doc/jwst_git/stat_summary.csv'
```

https://ssb.stsci.edu/pandokia/pandokia.cgi?query=detail&key_id=44103670

```
  File "/data4/iraf_conda/bldtmp/porcelain.OiakD22947/porcelain/envs/dev/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/data4/iraf_conda/bldtmp/porcelain.OiakD22947/porcelain/envs/dev/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/data1/jwst_rt/general/pipelines/test_miri_lrs_bkgnod.py", line 16, in test_miri_lrs_bkgnod
    config_file='calwebb_spec2.cfg')
  File "/data4/iraf_conda/bldtmp/porcelain.OiakD22947/porcelain/envs/dev/lib/python2.7/site-packages/jwst-0.7.7.dev259-py2.7-linux-x86_64.egg/jwst/stpipe/step.py", line 445, in call
    return instance.run(*args)
  File "/data4/iraf_conda/bldtmp/porcelain.OiakD22947/porcelain/envs/dev/lib/python2.7/site-packages/jwst-0.7.7.dev259-py2.7-linux-x86_64.egg/jwst/stpipe/step.py", line 352, in run
    result = self.process(*args)
  File "/data4/iraf_conda/bldtmp/porcelain.OiakD22947/porcelain/envs/dev/lib/python2.7/site-packages/jwst-0.7.7.dev259-py2.7-linux-x86_64.egg/jwst/pipeline/calwebb_spec2.py", line 68, in process
    input_table = Lvl2Input(input)
  File "/data4/iraf_conda/bldtmp/porcelain.OiakD22947/porcelain/envs/dev/lib/python2.7/site-packages/jwst-0.7.7.dev259-py2.7-linux-x86_64.egg/jwst/pipeline/calwebb_spec2.py", line 245, in __init__
    self.interpret_image_model(datamodels.open(input))
  File "/data4/iraf_conda/bldtmp/porcelain.OiakD22947/porcelain/envs/dev/lib/python2.7/site-packages/jwst-0.7.7.dev259-py2.7-linux-x86_64.egg/jwst/datamodels/util.py", line 88, in open
    **kwargs)
  File "/data4/iraf_conda/bldtmp/porcelain.OiakD22947/porcelain/envs/dev/lib/python2.7/site-packages/jwst-0.7.7.dev259-py2.7-linux-x86_64.egg/jwst/datamodels/container.py", line 71, in __init__
    raise IOError('Cannot open files.')
IOError(u'Cannot open files.',)
```

**Comment by hbushouse** [comment]
The first one is a result of our switching the jwst docs build from the old svn repo to the new git repo about 8-10 months ago. The old docs build system apparently created a custom stat_summary.csv file that contained a summary (pass/fail) status for every doc, from which the pandokia system then generated its report. The new doc build running on the git repo does not appear to generate this file, hence the error.

Need someone like @jhunkeler (or suitable surrogate) who knows how the new doc build works to figure out how to fix this. Or just leave the doc build out of the pandokia results.

**Comment by hbushouse** [comment]
I'm well aware of the existence of the 2nd error (I actually do check the test results every day, even without receiving an annoying email reminder) and is do to a recent change in the jwst asn_load infrastructure. It's in the queue to be worked.

**Comment by pllim** [comment]
![](https://i.ytimg.com/vi/X95d1KVlwwo/hqdefault.jpg)

**Comment by pllim** [comment]
@nden is right, JWST tests have fallen off pandokia-land (due to some C lib update).
