### ISSUE TITLE
tweakreg fails with current JWST imaging gwcs WCS objects

### ISSUE THREAD

**Issue by jdavies-st** [STScI-JWST/jwst#705]
JWST imaging data from NIRCam and MIRI have gwcs transforms that are no longer compatible with the SimpleWCS class in tweakreg.  When running any of this data through tweakreg, we get errors like the following:

```
2017-02-21 11:07:43,195 - stpipe.Image3Pipeline.tweakreg - INFO - Step tweakreg running with args (<jwst.datamodels.container.ModelContainer object at 0x7ff5b939ba90>,).
----------------------------------------------------------------------
ERROR RUNNING STEP 'Image3Pipeline':
    'V23ToSky' object has no attribute 'submodel_names'
Traceback (most recent call last):
  File "jwst/stpipe/cmdline.py", line 312, in step_from_cmdline
    step.run(*positional)
  File "jwst/stpipe/step.py", line 352, in run
    result = self.process(*args)
  File "jwst/pipeline/calwebb_image3.py", line 63, in process
    input_models = self.tweakreg(input_models)
  File "jwst/stpipe/step.py", line 352, in run
    result = self.process(*args)
  File "jwst/tweakreg/tweakreg_step.py", line 93, in process
    wcsimlist = list(map(self._imodel2wcsim, g))
  File "jwst/tweakreg/tweakreg_step.py", line 138, in _imodel2wcsim
    meta={'image_model': image_model}
  File "jwst/tweakreg/wcsimage.py", line 84, in __init__
    self.wcs = wcs
  File "jwst/tweakreg/wcsimage.py", line 107, in wcs
    self._swcs = SimpleWCS(wcs, copy=False)
  File "jwst/tweakreg/simplewcs.py", line 54, in __init__
    self.check_wcs(wcs)
  File "jwst/tweakreg/simplewcs.py", line 105, in check_wcs
    if len(tran.submodel_names) != 7:
AttributeError: 'V23ToSky' object has no attribute 'submodel_names'
```

Fixing this will require standardization of the transforms in some way or a more generalized approach to modifying the transforms in tweakreg.  Currently the JWST imaging transforms are in flux, so I expect fixes will first have to occur in assign_wcs before any fixes can be made to tweakreg.

**Comment by nden** [comment]
Tweakreg does not use the JWST WCS object and has its own implementation of WCS. There needs to be a discussion of what it needs and how to do it. For this the imaging WCS is stable enough IMHO.

**Comment by hbushouse** [comment]
Tracking this as a B7.2 task now in #1050.
