### ISSUE TITLE
assign_wcs step crashes with KeyError for 'bzero'

### ISSUE THREAD

**Issue by PaddyKavanagh** [STScI-JWST/jwst#898]
### Running assign_wcs gives an  @error:

strun cfgs/assign_wcs.cfg test_rate.fits

2017-05-17 14:09:07,958 - stpipe.assign_wcs - INFO - AssignWcsStep instance created.
2017-05-17 14:09:09,466 - stpipe.assign_wcs - INFO - Prefetch for CAMERA reference file is 'N/A'.
2017-05-17 14:09:09,467 - stpipe.assign_wcs - INFO - Prefetch for COLLIMATOR reference file is 'N/A'.
2017-05-17 14:09:09,467 - stpipe.assign_wcs - INFO - Prefetch for DISPERSER reference file is 'N/A'.
2017-05-17 14:09:09,467 - stpipe.assign_wcs - INFO - Prefetch for DISTORTION reference file is '/Users/patrickkavanagh/crds_mirror/references/jwst/miri/jwst_miri_distortion_0016.asdf'.
2017-05-17 14:09:09,467 - stpipe.assign_wcs - INFO - Prefetch for FILTEROFFSET reference file is 'N/A'.
2017-05-17 14:09:09,467 - stpipe.assign_wcs - INFO - Prefetch for FORE reference file is 'N/A'.
2017-05-17 14:09:09,467 - stpipe.assign_wcs - INFO - Prefetch for FPA reference file is 'N/A'.
2017-05-17 14:09:09,467 - stpipe.assign_wcs - INFO - Prefetch for IFUFORE reference file is 'N/A'.
2017-05-17 14:09:09,467 - stpipe.assign_wcs - INFO - Prefetch for IFUPOST reference file is 'N/A'.
2017-05-17 14:09:09,467 - stpipe.assign_wcs - INFO - Prefetch for IFUSLICER reference file is 'N/A'.
2017-05-17 14:09:09,467 - stpipe.assign_wcs - INFO - Prefetch for MSA reference file is 'N/A'.
2017-05-17 14:09:09,467 - stpipe.assign_wcs - INFO - Prefetch for OTE reference file is 'N/A'.
2017-05-17 14:09:09,467 - stpipe.assign_wcs - INFO - Prefetch for REGIONS reference file is '/Users/patrickkavanagh/crds_mirror/references/jwst/miri/jwst_miri_regions_0009.asdf'.
2017-05-17 14:09:09,467 - stpipe.assign_wcs - INFO - Prefetch for SPECWCS reference file is '/Users/patrickkavanagh/crds_mirror/references/jwst/miri/jwst_miri_specwcs_0009.asdf'.
2017-05-17 14:09:09,467 - stpipe.assign_wcs - INFO - Prefetch for V2V3 reference file is '/Users/patrickkavanagh/crds_mirror/references/jwst/miri/jwst_miri_v2v3_0009.asdf'.
2017-05-17 14:09:09,467 - stpipe.assign_wcs - INFO - Prefetch for WAVELENGTHRANGE reference file is '/Users/patrickkavanagh/crds_mirror/references/jwst/miri/jwst_miri_wavelengthrange_0002.asdf'.
2017-05-17 14:09:09,505 - stpipe.assign_wcs - INFO - Step assign_wcs running with args ('test_rate.fits',).
----------------------------------------------------------------------
ERROR RUNNING STEP 'AssignWcsStep':
    u'bzero'
Traceback (most recent call last):
  File "/Users/patrickkavanagh/anaconda/envs/jwst/lib/python2.7/site-packages/jwst-0.7.7.dev624-py2.7-macosx-10.7-x86_64.egg/jwst/stpipe/cmdline.py", line 312, in step_from_cmdline
    step.run(*positional)
  File "/Users/patrickkavanagh/anaconda/envs/jwst/lib/python2.7/site-packages/jwst-0.7.7.dev624-py2.7-macosx-10.7-x86_64.egg/jwst/stpipe/step.py", line 352, in run
    result = self.process(*args)
  File "/Users/patrickkavanagh/anaconda/envs/jwst/lib/python2.7/site-packages/jwst-0.7.7.dev624-py2.7-macosx-10.7-x86_64.egg/jwst/assign_wcs/assign_wcs_step.py", line 60, in process
    result = load_wcs(input_model, reference_file_names)
  File "/Users/patrickkavanagh/anaconda/envs/jwst/lib/python2.7/site-packages/jwst-0.7.7.dev624-py2.7-macosx-10.7-x86_64.egg/jwst/assign_wcs/assign_wcs.py", line 30, in load_wcs
    pipeline = mod.create_pipeline(input_model, reference_files)
  File "/Users/patrickkavanagh/anaconda/envs/jwst/lib/python2.7/site-packages/jwst-0.7.7.dev624-py2.7-macosx-10.7-x86_64.egg/jwst/assign_wcs/miri.py", line 36, in create_pipeline
    pipeline = exp_type2transform[exp_type](input_model, reference_files)
  File "/Users/patrickkavanagh/anaconda/envs/jwst/lib/python2.7/site-packages/jwst-0.7.7.dev624-py2.7-macosx-10.7-x86_64.egg/jwst/assign_wcs/miri.py", line 250, in ifu
    det2abl = (detector_to_abl(input_model, reference_files)).rename(
  File "/Users/patrickkavanagh/anaconda/envs/jwst/lib/python2.7/site-packages/jwst-0.7.7.dev624-py2.7-macosx-10.7-x86_64.egg/jwst/assign_wcs/miri.py", line 297, in detector_to_abl
    bzero = f.tree['bzero']
KeyError: u'bzero'

**Comment by nden** [comment]
We are reworking part of the MRS WCS pipeline to fix a problem with the inverse transforms. This involves a change to the reference files and currently the cal code and the reference files are out of sync. David will deliver the reference files soon. We are also taking the opportunity to rework the WCS ref files to use schemas and models and be more consistent in structure with the rest of the reference files #888

**Comment by PaddyKavanagh** [comment]
Thanks for the update Nadia. Do you have an idea of how long this will take?

**Comment by nden** [comment]
The files can be ready next week. It will probably take another week to put them in CRDS because some people are at PYCON.

**Comment by nden** [comment]
I'll post here when the new files are in CRDS.

**Comment by nden** [comment]
@PaddyKavanagh @baileyji MIRI reference files are now in CRDS and the cal code has been updated to use them.
