### ISSUE TITLE
outlier_detection in Image3Pipeline fails

### ISSUE THREAD

**Issue by PaddyKavanagh** [STScI-JWST/jwst#975]
Image3Pipeline is failing at outlier_detection with the trace below. The input is a two-point dither in an association file.

I am using the Build 7.1rc1 from a few days ago with CRDS_CONTEXT=jwst_0341.pmap

2017-06-12 19:18:07,115 - stpipe.Image3Pipeline.outlier_detection - INFO - Step outlier_detection running with args (<jwst.datamodels.container.ModelContainer object at 0x121c17c90>,).
----------------------------------------------------------------------
ERROR RUNNING STEP 'Image3Pipeline':
    unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/Users/patrickkavanagh/anaconda/envs/jwst_dev/lib/python2.7/site-packages/jwst-0.7.8rc1.dev1-py2.7-macosx-10.7-x86_64.egg/jwst/stpipe/cmdline.py", line 320, in step_from_cmdline
    step.run(*positional)
  File "/Users/patrickkavanagh/anaconda/envs/jwst_dev/lib/python2.7/site-packages/jwst-0.7.8rc1.dev1-py2.7-macosx-10.7-x86_64.egg/jwst/stpipe/step.py", line 356, in run
    result = self.process(*args)
  File "/Users/patrickkavanagh/anaconda/envs/jwst_dev/lib/python2.7/site-packages/jwst-0.7.8rc1.dev1-py2.7-macosx-10.7-x86_64.egg/jwst/pipeline/calwebb_image3.py", line 81, in process
    input_models = self.outlier_detection(input_models)
  File "/Users/patrickkavanagh/anaconda/envs/jwst_dev/lib/python2.7/site-packages/jwst-0.7.8rc1.dev1-py2.7-macosx-10.7-x86_64.egg/jwst/stpipe/step.py", line 356, in run
    result = self.process(*args)
  File "/Users/patrickkavanagh/anaconda/envs/jwst_dev/lib/python2.7/site-packages/jwst-0.7.8rc1.dev1-py2.7-macosx-10.7-x86_64.egg/jwst/outlier_detection/outlier_detection_step.py", line 73, in process
    step.do_detection()
  File "/Users/patrickkavanagh/anaconda/envs/jwst_dev/lib/python2.7/site-packages/jwst-0.7.8rc1.dev1-py2.7-macosx-10.7-x86_64.egg/jwst/outlier_detection/outlier_detection.py", line 117, in do_detection
    blendheaders=False, **pars)
  File "/Users/patrickkavanagh/anaconda/envs/jwst_dev/lib/python2.7/site-packages/jwst-0.7.8rc1.dev1-py2.7-macosx-10.7-x86_64.egg/jwst/resample/resample.py", line 73, in __init__
    self.output_wcs = resample_utils.make_output_wcs(self.input_models)
  File "/Users/patrickkavanagh/anaconda/envs/jwst_dev/lib/python2.7/site-packages/jwst-0.7.8rc1.dev1-py2.7-macosx-10.7-x86_64.egg/jwst/resample/resample_utils.py", line 61, in make_output_wcs
    output_wcs = assign_wcs.util.wcs_from_footprints(input_models)
  File "/Users/patrickkavanagh/anaconda/envs/jwst_dev/lib/python2.7/site-packages/jwst-0.7.8rc1.dev1-py2.7-macosx-10.7-x86_64.egg/jwst/assign_wcs/util.py", line 116, in wcs_from_footprints
    wcsinfo = pointing.wcsinfo_from_model(refmodel)
  File "/Users/patrickkavanagh/anaconda/envs/jwst_dev/lib/python2.7/site-packages/jwst-0.7.8rc1.dev1-py2.7-macosx-10.7-x86_64.egg/jwst/assign_wcs/pointing.py", line 90, in wcsinfo_from_model
    for ax in range(1, wcsaxes + 1):
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

**Comment by jdavies-st** [comment]
Hi @PaddyKavanagh what does the `gwcs` object look like in your MIRI images? And are the `meta.wcsinfo` keywords consistent with the `gwcs` object?  I assume `Image2Pipeline` (or at least `assign_wcs`) was run on the data first and produced the expected mapping from detector to sky?

Perhaps you can share the data so we can take a look?

**Comment by PaddyKavanagh** [comment]
Hi @jdavies-st. Yes, the simulation files calibrated using SloperPipeline and Image2Pipeline. I'm not sure how to check the gwcs info.  Both the _cal.fits files and the association file can be fetched from here:

https://www.dropbox.com/s/ssj0bmwj653mpo3/ima_2point_dither.zip?dl=0

**Comment by jdavies-st** [comment]
Thanks!

It looks like you're missing `.meta.wcsinfo.wcsaxes` in the sim data.  It should be set to `2` for imaging.

Also, it looks like there's lots of other data missing in your `wcsinfo` block.  Here's what a typical `meta.wcsinfo` block from a NIRCam sim image looks like:
```
{'cdelt1': 8.57480833333333e-06,
 'cdelt2': 8.59685555555555e-06,
 'crpix1': 1024.5,
 'crpix2': 1024.5,
 'crval1': 5.831816666666667,
 'crval2': -71.98830272222223,
 'ctype1': 'RA---TAN',
 'ctype2': 'DEC--TAN',
 'cunit1': 'deg',
 'cunit2': 'deg',
 'dec_ref': -71.98830272222223,
 'pc1_1': -0.9999999762414795,
 'pc1_2': 0.000217984037025379,
 'pc2_1': 0.000217984037025379,
 'pc2_2': 0.9999999762414795,
 'ra_ref': 5.831816666666667,
 'roll_ref': 359.9550305654217,
 'v2_ref': 52.276773,
 'v3_ref': -459.809697,
 'v3yangle': 0.057459,
 'vparity': -1,
 'wcsaxes': 2}
```
Some of these can be populated from the SIAF, so `cdelt1, cdelt2, v2_ref, v3_ref, v3yangle, vparity` etc.  I cleaned up some MIRI sim data a while back so I could use it for testing.  My clean-up script:
```
from jwst import datamodels

from glob import glob

for f in glob('*_cal.fits'):
    a = datamodels.open(f)
    a.meta.wcsinfo.cdelt1 = 0.110459 / 3600
    a.meta.wcsinfo.cdelt2 = 0.111481 / 3600
    a.meta.wcsinfo.pc1_1 = -1.0
    a.meta.wcsinfo.wcsaxes = 2
    a.meta.wcsinfo.ctype1 = 'RA--TAN '
    a.meta.wcsinfo.ctype2 = 'DEC--TAN'
    a.meta.wcsinfo.cunit1 = 'deg     '
    a.meta.wcsinfo.cunit2 = 'deg     '
    a.meta.wcsinfo.vparity = -1
    a.meta.wcsinfo.v3yangle = 5.0152
    a.meta.wcsinfo.crpix1 = a.meta.wcsinfo.ra_ref
    a.meta.wcsinfo.crpix2 = a.meta.wcsinfo.dec_ref
    a.save(a.meta.filename)
```
That got me going.  It might be worthwhile letting the sim folks know that this information needs to be put in at the beginning.  The MIRI SIAF is the location for most of it.

Hope this helps!  - James

**Comment by hbushouse** [comment]
The ctype1 value should have 3 dashes in the middle, i.e. "RA---TAN". The convention is "ABCD-XYZ" with any unneeded char's replaced by a dash. So for RA and Dec you get "RA---TAN" and "DEC--TAN".

**Comment by PaddyKavanagh** [comment]
Thanks James and Howard, for the info and the code!

**Comment by jdavies-st** [comment]
Thanks for catching that Howard!  I should have run `fitsverify` on my output, which would have caught that.

@philhodge points out to me that it would be good to close the datamodels if you have lots of them.  So the last line
```
a.close()
```
But I seem to recall `datamodels.close()` being a bit of a chimera in terms of whether or not it releases file handles.  I should have used a `with` block instead probably.

**Comment by jdavies-st** [comment]
Anyway, let us know if fixing these issues allows you to proceed in `Image3Pipeline`.  I just did the changes myself to `meta` in your files, re-ran `assign_wcs`, and now the dataset seems to run through the pipeline well, breezing through `outlier_detection` and `resample` OK, but it barfs on `source_catalog`.  Hmm.  I will open an issue on that.

**Comment by philhodge** [comment]
I looked up what the `with` statement does when the statement has been completed:  it calls the context manager's __exit__ method.  astropy.io.fits defines __exit__ in more than one place, e.g. in hdulist.py, and they all call close().  So for astropy.io.fits, at least, it should be safe to call close().

**Comment by jdavies-st** [comment]
Thanks Phil!

In the case above, `DataModel.__exit__()` calls `DataModel.close()`, which then proceeds to call `close()` on the `HDUList` instance.  But for some reason the `HDUList` instance is empty when one reads in a DataModel, so `close` is not doing anything right now.  Hmm.

**Comment by jdavies-st** [comment]
Closing issue, as I think we've addressed everything here.  If there's further problems related to this dataset, please reopen.
